{{- if eq .Values.cloudprovider "pve" }}
{{- range $index, $nodepool := .Values.nodepools }}
apiVersion: rke-machine-config.cattle.io/v1
kind: PveConfig
metadata:
  name: {{ $.Values.cluster.name }}-{{ $nodepool.name }}
  namespace: fleet-default
fullClone: {{ $nodepool.fullClone }}
insecureTls: {{ $nodepool.insecureTLs }}
isoDevice: {{ $nodepool.isoDevice }}
memory: {{ $nodepool.memory | quote }}
networkInterface: {{ $nodepool.networkInterface }}
processorCores: {{ $nodepool.processorCores | quote }}
processorSockets: {{ $nodepool.processorSockets | quote }}
resourcePool: {{ $nodepool.resourcePool }}
sshUser: {{ $nodepool.sshUser }}
template: {{ $nodepool.template | quote }}
---
{{- end }}
{{ $nodepool := .Values.nodepool }}
{{- if $nodepool }}
apiVersion: rke-machine-config.cattle.io/v1
kind: PveConfig
metadata:
  name: {{ .Values.cluster.name }}-{{ $nodepool.name }}
  namespace: fleet-local
fullClone: {{ $nodepool.fullClone }}
insecureTls: {{ $nodepool.insecureTLs }}
isoDevice: {{ $nodepool.isoDevice }}
memory: {{ $nodepool.memory | quote }}
networkInterface: {{ $nodepool.networkInterface }}
processorCores: {{ $nodepool.processorCores | quote }}
processorSockets: {{ $nodepool.processorSockets | quote }}
resourcePool: {{ $nodepool.resourcePool }}
sshUser: {{ $nodepool.sshUser }}
template: {{ $nodepool.template | quote }}
{{- end }}
{{- end }}

